### PR TITLE
Accessibility is important here!!

### PR DESCRIPTION
**Pull request by brettz9**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Hehe. I know this is a joke, but it actually makes it worse. Currently, a screen reader would skip the image and just read "loading", but now it will read "fidget spinner ... loading".

**Comment by brettz9** [comment]
Actually I think it'd be even worse than that. While it looks like and has been used as a fidget spinner, it is actually "NKo Symbol Gbakurunen", a symbol of the (RTL) West-African script, N'Ko, so unless accessibility tools are aware of such emoji reinterpretations, I guess it might just read the symbol name (or pronounce it?).

Btw, how would it read out "loading"? Just for any image?

**Comment by sindresorhus** [comment]
> Btw, how would it read out "loading"? Just for any image?

https://github.com/sindresorhus/sindresorhus/blame/03abe3452874fc1d0839c2f03a2d5e26c7b8434c/readme.md#L7

**Comment by papb** [comment]
@sindresorhus That's a clever way to link to a specific line in a `.md` file, thanks. I never thought of using blame to work around that.

I wish GitHub would detect `/#L\d+$/` in the URL and display the readme as a raw file instead of rendering as markdown...

**Pull request closed without merging**
