### PR TITLE
Fix ASAP

### PR DESCRIPTION
**Pull request by szmarczak**
https://github.com/szmarczak/sindresorhus/blob/patch-1/readme.md It should do the job but I don't know for how long it will be fixed.

### CODE REVIEW

**Comment by sindresorhus** [comment]
I’m gonna try this one later. Keep open.

**Comment by ovflowd** [comment]
Sorry, but I'm gonna steal this 👀

**Comment by szmarczak** [comment]
[GitHub is having some issues.](https://www.githubstatus.com/incidents/j597fw8kv04c) I think it's a perfect time to merge this :P

**Comment by KhushrajRathod** [comment]
Hi, do you think there's any way to load for say, 10 seconds before showing this? 
That would be awesome!

Things I've already tried

- [x] <script> - No user scripts on github
- [x] Full gif - Not responsive design

Any ideas?

**Review by khrj — CHANGES_REQUESTED** [review]
[removed]

**Comment by sindresorhus** [comment]
@szmarczak Can you change the links to link to something fun? We don't want users to bother GitHub support.

**Comment by sindresorhus** [comment]
@KhushrajRathod I would just go with an animated GIF. If you don't make it wide, it should work OK on mobile too.

**Comment by KhushrajRathod** [comment]
@szmarczak Try these links:
https://github.com/KhushrajRathod/KhushrajRathod/blob/master/README.md

**Comment by szmarczak** [comment]
@sindresorhus Done :D

**Comment by szmarczak** [comment]
@KhushrajRathod IMO the annoying website is too brutal :P I have just tried it. SOOO ANNOYING 🤣

**Comment by KhushrajRathod** [comment]
> @KhushrajRathod IMO the annoying website is too brutal :P I have just tried it. SOOO ANNOYING 🤣 

😂😂 Idk what browser you used, but chrome on desktop produces the best results

**Comment by KhushrajRathod** [comment]
I've thought about something yesterday - Can GIF frames change sizes? Google only tells me how to optimize a GIF, but I need the GIF frame sizes to change. For e.g.

- GitHub loader GIF is on top, there's a GIF used for padding below it which is really long (vertically). The unicorn error HTML is after this padding GIF, but it's not in the view port, due to the length of the padding GIF

- Two seconds later the GitHub loader GIF shrinks it's size to 1 pixel, and the padding gif also shrinks it's size to 1 pixel, making users think the loader isn't there anymore, and the error HTML obviously moves up

What I don't know is whether GIFs can have frames with different sizes

For e.g.

- First 200 frames: 200x8000
- Next 800 frames: 2x2

@sindresorhus You have a [lot](https://github.com/sindresorhus/is-gif) [of](https://github.com/sindresorhus/kap-gifski) [experience](https://sindresorhus.com/jiffy) [with](https://sindresorhus.com/gifski) [GIFs](https://github.com/sindresorhus/gulp-imagemin) :D Any ideas? 

I've had a go with ImageMagick, I created a folder with frames of different sizes, but it didn't work :/

<details>
  <summary>Output (click to expand)</summary>

animated
</details>



Made using:

```
for i in {1..20}                              
do
    convert -size 2x8000 xc:black test${i}.png
done

for i in {21..40}                               
do
    convert -size 400x2 xc:black test${i}.png 
done

convert -delay 5 test*.png animated.gif
```

**Comment by sindresorhus** [comment]
Purrfect 🐈

**Comment by sindresorhus** [comment]
> Can GIF frames change sizes?

No, but just render everything into the GIF, including the HTML.

**Comment by ghost** [comment]
> https://github.com/szmarczak/sindresorhus/blob/patch-1/readme.md It should do the job but I don't know for how long it will be fixed.

**Review by Prana111025 — COMMENTED** [review]
Aline

**Pull request merged**
