### PR TITLE
Try to load the content for 10 seconds

### PR DESCRIPTION
**Pull request by Richienb**
Try to load the readme content for 10 seconds before giving up.

[Preview](https://github.com/Richienb/Richienb/tree/e68524a51bf6fc24b86f81f7bf5c62cb5dc115b2#readme)

// @sindresorhus

### CODE REVIEW

**Comment by sindresorhus** [comment]
Haha. Clever.

**Comment by sindresorhus** [comment]
Does it actually work though? Doesn't seem to render here: https://github.com/Richienb/sindresorhus/tree/try-load

**Comment by Richienb** [comment]
@sindresorhus That's because it depends on the image being located in your repository

https://github.com/sindresorhus/sindresorhus/pull/9/files#diff-0730bb7c2e8f9ea2438b52e419dd86c9R2

**Comment by sindresorhus** [comment]
The links no longer work though, since clicking it just links the image. Maybe you could linkify the image to https://www.youtube.com/watch?v=dQw4w9WgXcQ ?

**Comment by Richienb** [comment]
@sindresorhus Replace the img tag in the readme with

```html
	<a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ"><img src="https://github.com/sindresorhus/sindresorhus/raw/master/info.svg?sanitize=true"></a>
```

**Review by Boludo12 — COMMENTED** [review]
No

**Pull request merged**
